services:
  postgres:
    image: postgres:17.2
    container_name: base-ts-express
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      TZ: Asia/Tokyo
    ports:
      - '15432:5432'
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
      - ./docker/postgres/docker-entrypoint-initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql
